adminUser:
  password: vault:tf-jx-wired-minnow/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: j_ronquillo@u.pacific.edu
  token: vault:tf-jx-wired-minnow/pipelineUser:token
  username: sindack
prow:
  hmacToken: vault:tf-jx-wired-minnow/prow:hmacToken
